name: Build

on: [push, pull_request]

jobs:
  build:    
    strategy:
      matrix:
        agent: ['ubuntu-latest', 'windows-latest','macos-latest']
    runs-on: ${{matrix.agent}}
    name: Build on ${{matrix.agent}}
    steps:
    - uses: actions/checkout@v2    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Test
      run: dotnet test --configuration Release 
