name: Sonar

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2    
    - name: Setup .NET Core for Sonar
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.805
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install Sonar
      run: dotnet tool install --global dotnet-sonarscanner --version 4.8.0
    - name: Start Sonar
      run: dotnet-sonarscanner begin /k:"web-partes" /o:"aldakin" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.exclusions="**/wwwroot/lib/**" /d:sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=OpenCover
    - name: End Sonar
      run: dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}" 
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
